name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-test:
    uses: liquibase/build-logic/.github/workflows/pro-extension-test.yml@v0.7.4
    secrets: inherit
    with:
      os: '["ubuntu-latest"]'
      java: "[11, 17, 18]"
