name: Ephemeral Cloud Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy-ephemeral-cloud-infra:
    uses: liquibase/build-logic/.github/workflows/ephemeral-cloud-infra.yml@DAT-16824
    secrets: inherit
    with:
        action: deploy

  destroy-ephemeral-cloud-infra:
    uses: liquibase/build-logic/.github/workflows/ephemeral-cloud-infra.yml@DAT-16824
    secrets: inherit
    with:
        action: destroy
