name: Ephemeral Cloud Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy-ephemeral-cloud-infra:
    uses: liquibase/build-logic/.github/workflows/ephemeral-cloud-infra.yml@DAT-16824
    secrets: inherit
    with:
        deploy: true
        dynamodb: true

  destroy-ephemeral-cloud-infra:
    if: always()
    needs: deploy-ephemeral-cloud-infra
    uses: liquibase/build-logic/.github/workflows/ephemeral-cloud-infra.yml@DAT-16824
    secrets: inherit
    with:
        destroy: true
        stack_id: ${{ needs.deploy-ephemeral-cloud-infra.outputs.stack_id }}
        dynamodb: true

